name: version-bump

on:
  push:
    branches: [main]

jobs:
  version-bump:
    name: version-bump
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: phips28/gh-action-bump-version@v8.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
